### ISSUE TITLE
Githubaction - sbt error - class java.io.IOException cannot be cast to class xsbti.FullReload

### ISSUE THREAD

**Issue by regis-leray** [djspiewak/sbt-github-actions#88]
sbt 1.5.5
sbt github action 0.13.0

When i trying to run a built on github im getting this weird error , does anyone have any clue ?

### stack trace
```log
Run sbt ++2.13.6 githubWorkflowCheck
downloading sbt launcher 1.5.5
copying runtime jar...
[info] [launcher] getting org.scala-sbt sbt 1.5.5  (this may take some time)...
[info] [launcher] getting Scala 2.12.14 (for sbt)...
java.lang.ClassCastException: class java.io.IOException cannot be cast to class xsbti.FullReload (java.io.IOException is in module java.base of loader 'bootstrap'; xsbti.FullReload is in unnamed module of loader 'app')
	at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:59)
	at sbt.xMain.run(Main.scala:46)
	at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
	at xsbt.boot.Launch$.run(Launch.scala:149)
	at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
	at xsbt.boot.Launch$.launch(Launch.scala:159)
	at xsbt.boot.Launch$.apply(Launch.scala:44)
	at xsbt.boot.Launch$.apply(Launch.scala:21)
	at xsbt.boot.Boot$.runImpl(Boot.scala:78)
	at xsbt.boot.Boot$.run(Boot.scala:73)
	at xsbt.boot.Boot$.main(Boot.scala:21)
	at xsbt.boot.Boot.main(Boot.scala)
Error:  [launcher] error during sbt launcher: java.lang.ClassCastException: class java.io.IOException cannot be cast to class xsbti.FullReload (java.io.IOException is in module java.base of loader 'bootstrap'; xsbti.FullReload is in unnamed module of loader 'app')Run sbt ++2.13.6 githubWorkflowCheck
downloading sbt launcher 1.5.5
copying runtime jar...
[info] [launcher] getting org.scala-sbt sbt 1.5.5  (this may take some time)...
[info] [launcher] getting Scala 2.12.14 (for sbt)...
java.lang.ClassCastException: class java.io.IOException cannot be cast to class xsbti.FullReload (java.io.IOException is in module java.base of loader 'bootstrap'; xsbti.FullReload is in unnamed module of loader 'app')
	at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:59)
	at sbt.xMain.run(Main.scala:46)
	at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
	at xsbt.boot.Launch$.run(Launch.scala:149)
	at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
	at xsbt.boot.Launch$.launch(Launch.scala:159)
	at xsbt.boot.Launch$.apply(Launch.scala:44)
	at xsbt.boot.Launch$.apply(Launch.scala:21)
	at xsbt.boot.Boot$.runImpl(Boot.scala:78)
	at xsbt.boot.Boot$.run(Boot.scala:73)
	at xsbt.boot.Boot$.main(Boot.scala:21)
	at xsbt.boot.Boot.main(Boot.scala)
Error:  [launcher] error during sbt launcher: java.lang.ClassCastException: class java.io.IOException cannot be cast to class xsbti.FullReload (java.io.IOException is in module java.base of loader 'bootstrap'; xsbti.FullReload is in unnamed module of loader 'app')
```

### plugins.sbt
```scala
addSbtPlugin("org.xerial.sbt" % "sbt-pack" % "0.14")
addSbtPlugin("com.github.regis-leray" % "sbt-docker-image" % "0.7.1")
addSbtPlugin("com.github.sbt" % "sbt-ci-release"     % "1.5.10")
addSbtPlugin("com.codecommit" % "sbt-github-actions" % "0.13.0")
```

### build.sbt
```scala
val GraalVM11 = "graalvm-ce-java11@20.3.0"

ThisBuild / scalaVersion := "2.13.6"
ThisBuild / organization := "com.regis"
ThisBuild / Test / fork := true
ThisBuild / Test / parallelExecution := false
ThisBuild / githubWorkflowJavaVersions := Seq(GraalVM11)
ThisBuild / versionScheme := Some("early-semver")

ThisBuild / githubWorkflowBuildPreamble ++= Seq(
  WorkflowStep.Run(
    List(
      "docker-compose -f \"docker-compose.yml\" up -d --build",
    ),
    name = Some("Start containers")
  )
)

ThisBuild / githubWorkflowBuild := Seq(
  WorkflowStep.Sbt(List("test"))
)

//sbt-ci-release settings
ThisBuild / githubWorkflowPublishPreamble := Seq(
  WorkflowStep.Use(UseRef.Public("olafurpg", "setup-gpg", "v3"))
)

ThisBuild / githubWorkflowTargetTags ++= Seq("v*")
ThisBuild / githubWorkflowPublishTargetBranches := Seq(
  RefPredicate.StartsWith(Ref.Branch("master")),
  RefPredicate.StartsWith(Ref.Tag("v"))
)

val doobieVersion = "0.12.1"
val http4sVersion = "0.21.20"
val circeVersion = "0.13.0"
val csvVersion = "0.6.2"

lazy val root = (project in file("."))
  .settings(
    name := "ambassadors-service",
    scalacOptions ++= Seq(
      "-encoding", "UTF-8",
      "-unchecked",
      "-deprecation",
      "-feature",
      //"-Xlint",
      "-Xlint:_,-byname-implicit",
      "-Xfatal-warnings",
    ),
    scalacOptions ++= Seq(
      "-language:higherKinds",
      "-language:postfixOps",
    ),
    libraryDependencies ++= Seq(
      "org.http4s" %% "http4s-blaze-server" % http4sVersion,
      "org.http4s" %% "http4s-blaze-client" % http4sVersion,
      "org.http4s" %% "http4s-dsl" % http4sVersion,
      "org.http4s" %% "http4s-circe" % http4sVersion,

      "io.circe" %% "circe-core" % circeVersion,
      "io.circe" %% "circe-generic" % circeVersion,
      "io.circe" %% "circe-parser" % circeVersion,

      "org.tpolecat" %% "doobie-core" % doobieVersion,
      "org.tpolecat" %% "doobie-postgres" % doobieVersion,
      "org.tpolecat" %% "doobie-hikari" % doobieVersion,
      "org.tpolecat" %% "doobie-scalatest" % doobieVersion % Test,

      "com.github.fs2-blobstore" %% "s3" % "0.7.3",

      "com.sun.mail" % "javax.mail" % "1.6.2",
      "com.icegreen" % "greenmail" % "1.3" % Test,

      "com.typesafe" % "config" % "1.4.1",
      "org.flywaydb" % "flyway-core" % "7.2.0",

      "org.slf4j" % "slf4j-api" % "1.7.32",
      "org.apache.logging.log4j" % "log4j-api" % "2.13.3",
      "org.apache.logging.log4j" % "log4j-core" % "2.13.3",
      "org.apache.logging.log4j" % "log4j-slf4j-impl" % "2.13.3",

      "com.nrinaudo" %% "kantan.csv" % csvVersion,
      "com.nrinaudo" %% "kantan.csv-generic" % csvVersion,
      "com.nrinaudo" %% "kantan.csv-java8" % csvVersion,

      "org.scalatest" %% "scalatest" % "3.2.10" % Test
    ),
    packMain := Map(
      "ambassadors" -> "com.trampoline.xx.Server"
    )
  )
  .enablePlugins(PackPlugin, DockerImagePlugin)
```

**Comment by regis-leray** [comment]
im closing the issue since not related to the plugin

```
java.io.IOException: Could not create directory /home/runner/work/ambassadors/ambassadors/target/global-logging: java.nio.file.AccessDeniedException: /home/runner/work/ambassadors/ambassadors/target/global-logging

	at sbt.io.IO$.createDirectory(IO.scala:337)
	at sbt.StandardMain$.$anonfun$initialGlobalLogging$2(Main.scala:233)
	at sbt.StandardMain$.$anonfun$initialGlobalLogging$2$adapted(Main.scala:233)
	at scala.Option.foreach(Option.scala:407)
	at sbt.StandardMain$.$anonfun$initialGlobalLogging$1(Main.scala:233)
	at sbt.internal.io.Retry$.apply(Retry.scala:46)
	at sbt.internal.io.Retry$.apply(Retry.scala:28)
	at sbt.internal.io.Retry$.apply(Retry.scala:23)
	at sbt.StandardMain$.createTemp$1(Main.scala:232)
	at sbt.StandardMain$.$anonfun$initialGlobalLogging$3(Main.scala:238)
	at sbt.internal.util.GlobalLogBacking$.apply(GlobalLogging.scala:61)
	at sbt.internal.util.GlobalLogging$.initial(GlobalLogging.scala:88)
	at sbt.StandardMain$.initialGlobalLogging(Main.scala:239)
	at sbt.StandardMain$.initialGlobalLogging(Main.scala:242)
	at sbt.StandardMain$.initialState(Main.scala:272)
	at sbt.xMain$.$anonfun$run$11(Main.scala:126)
	at sbt.internal.util.Terminal$.withStreams(Terminal.scala:381)
	at sbt.xMain$.withStreams$1(Main.scala:87)
	at sbt.xMain$.run(Main.scala:121)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:57)
	at sbt.xMain.run(Main.scala:46)
	at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
	at xsbt.boot.Launch$.run(Launch.scala:149)
	at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
	at xsbt.boot.Launch$.launch(Launch.scala:159)
	at xsbt.boot.Launch$.apply(Launch.scala:44)
	at xsbt.boot.Launch$.apply(Launch.scala:21)
	at xsbt.boot.Boot$.runImpl(Boot.scala:78)
	at xsbt.boot.Boot$.run(Boot.scala:73)
	at xsbt.boot.Boot$.main(Boot.scala:21)
	at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.nio.file.AccessDeniedException: /home/runner/work/ambassadors/ambassadors/target/global-logging
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389)
	at java.base/java.nio.file.Files.createDirectory(Files.java:689)
	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:796)
	at java.base/java.nio.file.Files.createDirectories(Files.java:782)
	at sbt.io.IO$.$anonfun$createDirectory$1(IO.scala:333)
	at sbt.internal.io.Retry$.apply(Retry.scala:46)
	at sbt.internal.io.Retry$.apply(Retry.scala:28)
	at sbt.internal.io.Retry$.apply(Retry.scala:23)
	at sbt.io.IO$.createDirectory(IO.scala:335)
	... 35 more
```
