### ISSUE TITLE
MatrixExclusions don't seem to work with `JavaSpec`

### ISSUE THREAD

**Issue by vasilmkd** [djspiewak/sbt-github-actions#94]
From the Cats Effect 3 build:

This is how the build used to be (GraalVM was a String).
```scala
  // Nice-to-haves but unreliable in CI
  val flakyFilters = Seq(
    MatrixExclude(Map("os" -> Windows, "java" -> GraalVM))
  )
```

This now results in a compile error, which is fine, calling `.render` should fix it.

However, that results in the following error:
```
sbt:root> last githubWorkflowGenerate
[error] java.lang.RuntimeException: inclusion key `java` was present in matrix, but value `temurin@11` was not in List(JavaSpec(Temurin,8), JavaSpec(Temurin,11), JavaSpec(Temurin,17), JavaSpec(GraalVM(21.3),11))
[error]         at scala.sys.package$.error(package.scala:30)
[error]         at sbtghactions.GenerativePlugin$.$anonfun$compileJob$12(GenerativePlugin.scala:355)
[error]         at sbtghactions.GenerativePlugin$.$anonfun$compileJob$12$adapted(GenerativePlugin.scala:348)
[error]         at scala.collection.immutable.Map$Map2.foreach(Map.scala:273)
[error]         at sbtghactions.GenerativePlugin$.checkMatching$1(GenerativePlugin.scala:348)
[error]         at sbtghactions.GenerativePlugin$.$anonfun$compileJob$15(GenerativePlugin.scala:378)
[error]         at sbtghactions.GenerativePlugin$.$anonfun$compileJob$15$adapted(GenerativePlugin.scala:378)
[error]         at scala.collection.immutable.List.foreach(List.scala:431)
[error]         at sbtghactions.GenerativePlugin$.compileJob(GenerativePlugin.scala:378)
[error]         at sbtghactions.GenerativePlugin$.$anonfun$compileWorkflow$8(GenerativePlugin.scala:471)
[error]         at scala.collection.immutable.List.map(List.scala:293)
[error]         at sbtghactions.GenerativePlugin$.compileWorkflow(GenerativePlugin.scala:471)
[error]         at sbtghactions.GenerativePlugin$.$anonfun$generateCiContents$1(GenerativePlugin.scala:702)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error]         at java.base/java.lang.Thread.run(Thread.java:833)
[error] (githubWorkflowGenerate) inclusion key `java` was present in matrix, but value `temurin@11` was not in List(JavaSpec(Temurin,8), JavaSpec(Temurin,11), JavaSpec(Temurin,17), JavaSpec(GraalVM(21.3),11))
```

**Comment by djspiewak** [comment]
This is fixed in 0.14.1. I ran into it with the Cats build as well. Just need to catch up sbt-spiewak now.
